### ISSUE TITLE
[Estoria 35] - Instancia não encontrada retorna status 400

### ISSUE THREAD

**Issue by daimacedo** [adtsys-cloud/adt-instance-info#29]
Quando uma instancia não é encontrada com a configuração passada, o status retornado é 400, deveria ser 404 - not found. 
Nota: A mensagem retornada está correta, o problema é somente no status.

**Comment by Diones** [comment]
Corrigido.

**Comment by claudioed** [comment]
![print](https://cloud.githubusercontent.com/assets/4073304/15026301/29203abe-1214-11e6-8aaf-e358c7ae8919.png)

Corrigido
